### ISSUE TITLE
Snort version not in ET ruleset URL string

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shirkdog/pulledpork#130]
```
What steps will reproduce the problem?
1.  Run pulledpork.pl

What version of the product are you using? On what operating system?
Ubuntu 12.04LTS
PP v.0.6.1
Snort Version 2.9.4.1 GRE (Build 69)

Please provide any additional information below.


    http://code.google.com/p/pulledpork/
      _____ ____
     `----,\    )
      `--==\\  /    PulledPork v0.6.1 the Smoking Pig <////~
       `--==\\/
     .-~~~~-.Y|\\_  Copyright (C) 2009-2011 JJ Cummings
  @_/        /  66\_  cummingsj@gmail.com
    |    \   \   _(")
     \   /-| ||'--'  Rules give me wings!
      \_\  \_\\
```

Checking latest MD5 for snortrules-snapshot-2941.tar.gz....
        They Match
        Done!
Prepping rules from snortrules-snapshot-2941.tar.gz for work....
        Done!
Checking latest MD5 for opensource.gz....
        They Match
        Done!
Prepping rules from opensource.gz for work....
        Done!
Use of uninitialized value $Snortv in substitution (s///) at 
/home/user/pulledpork-0.6.1/./pulledpork.pl line 1748.
Use of uninitialized value $Snortv in concatenation (.) or string at 
/home/travis/pulledpork-0.6.1/./pulledpork.pl line 1749.
Checking latest MD5 for emerging.rules.tar.gz....
        Error 500 when fetching https://rules.emergingthreats.net/open/snort-/emerging.rules.tar.gz.md5 at /home/user/pulledpork-0.6.1/./pulledpork.pl line 453
        main::md5file('open', 'emerging.rules.tar.gz', '/tmp/', 'https://rules.emergingthreats.net/open/snort-/') called at /home/user/pulledpork-0.6.1/./pulledpork.pl line 1758

```

Original issue reported on code.google.com by `tjlaws5...@gmail.com` on 16 Apr 2013 at 3:30
```

**Comment by shirkdog** [comment]
This should have been addressed.
