### ISSUE TITLE
Check for bad/missing md5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shirkdog/pulledpork#143]
```
version 0.7; when no md5 is available, or when it's blank or not a md5 sum (32 
charectors) skip the process for that ruleset.

Right now pp loops trying to verify the download and it can't (since the md5 is 
bad/gone/blank).

```

Original issue reported on code.google.com by `jth...@gmail.com` on 23 Oct 2013 at 5:56

**Comment by finchy** [comment]
This has been rectified by providing an md5 for all rulesets on Snort.org.  This doesn't fix the "issue" with pulledpork, but it should mitigate it.

**Comment by shirkdog** [comment]
... and any other signature set needs to provide an MD5 for whatever ruleset.
