### ISSUE TITLE
Move from LWP to CURL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shirkdog/pulledpork#152]
```
Perl's LWP module has a documented list of problems when working with proxies - 
doesn't support NTLM auth, incorrectly uses GET https://www.snort.org/... 
instead of CONNECT www.snort.org:443, etc.

I propose that curl be used instead. I have hacked the latest pulledpork to 
work with WWW::Curl::Simple.
```

Original issue reported on code.google.com by `konrads....@gmail.com` on 12 Mar 2014 at 12:28

Attachments:
* [pulledpork.pl](https://storage.googleapis.com/google-code-attachments/pulledpork/issue-152/comment-0/pulledpork.pl)

**Comment by shirkdog** [comment]
Closing this, as proxy support has been updated.
