### ISSUE TITLE
Modifying snort rules 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shirkdog/pulledpork#172]
```
Dear All !

I have tuned some of the snort according to my requirement. Now i want to 
update my snort rules.
i am using pulled pork for this purpose. Now i am worried that if i will update 
the rules with pulled pork it will overwrite my tuned rules .

is there any way to prevent these rules from modifying !


Thanks !
Said.W
```

Original issue reported on code.google.com by `saidwali...@gmail.com` on 28 Mar 2015 at 6:41

**Comment by shirkdog** [comment]
Closing this, pullledpork will only change what you tell it to. If you have changed default rules with your own edits, you need to have those modifications in pulledpork so it will automatically tune your rules for you.
