### ISSUE TITLE
pp confused by content/pcre options that have sid:\d as a substring

### ISSUE THREAD

**Issue by StephenHepp** [shirkdog/pulledpork#181]
i ran pulledpork.pl -c pp.conf and got the latest v2962 rules
next i deleted /tmp/snortrules*
then i ran pulledpork.pl again

I expected the var/log/sid_changes.log to show me 0 new/modified rules since actually it was re-processing the same snort package but instead it showed me many activex rules were "new"

these same rules show up every time pp processes a rule package

i suspect this is because those rules have content/pcre matches something like this:
content:"clsid:0D43FE01

i tried replacing the regexes in pulledpork.pl that refer to sid: with
 [;\s]sid\s*:\s*\d{3,5}\s*;
but that didn't seem to fix this problem.

**Comment by shirkdog** [comment]
Does this occur with the latest 2.9.7.3 rules? 

Also, provide the command line you are running.

**Comment by StephenHepp** [comment]
same issue with 2973

############Full download of 2973
[shepp@shepp-ws snort]$ rm /tmp/snortrules*
[shepp@shepp-ws snort]$ ./pulledpork/pulledpork.pl -c pp.conf

Use of uninitialized value $Snort_path in -B at ./pulledpork/pulledpork.pl line 1650.
Checking latest MD5 for snortrules-snapshot-2973.tar.gz....
Rules tarball download of snortrules-snapshot-2973.tar.gz....
	They Match
	Done!
Prepping rules from snortrules-snapshot-2973.tar.gz for work....
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
	Done!
Reading rules...
Activating balanced rulesets....
	Done
Setting Flowbit State....
	Enabled 557 flowbits
	Enabled 1 flowbits
	Done
Writing /home/shepp/snort/rules/snort.rules....
	Done
Generating sid-msg.map....
	Done
Writing v1 /home/shepp/snort/sid-msg.map....
	Done
Writing /home/shepp/snort/var/log/sid_changes.log....
	Done
Rule Stats...
	New:-------24414
	Deleted:---0
	Enabled Rules:----7067
	Dropped Rules:----0
	Disabled Rules:---17347
	Total Rules:------24414
No IP Blacklist Changes

Done
############Re-download of 2973
[shepp@shepp-ws snort]$ rm /tmp/snortrules-snapshot-2973.tar.gz*
[shepp@shepp-ws snort]$ ./pulledpork/pulledpork.pl -c pp.conf

Use of uninitialized value $Snort_path in -B at ./pulledpork/pulledpork.pl line 1650.
Checking latest MD5 for snortrules-snapshot-2973.tar.gz....
Rules tarball download of snortrules-snapshot-2973.tar.gz....
	They Match
	Done!
Prepping rules from snortrules-snapshot-2973.tar.gz for work....
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
Use of uninitialized value $Distro in concatenation (.) or string at ./pulledpork/pulledpork.pl line 255.
	Done!
Reading rules...
Reading rules...
Activating balanced rulesets....
	Done
Setting Flowbit State....
	Enabled 557 flowbits
	Enabled 1 flowbits
	Done
Writing /home/shepp/snort/rules/snort.rules....
	Done
Generating sid-msg.map....
	Done
Writing v1 /home/shepp/snort/sid-msg.map....
	Done
Writing /home/shepp/snort/var/log/sid_changes.log....
	Done
Rule Stats...
	New:-------47
	Deleted:---16
	Enabled Rules:----7067
	Dropped Rules:----0
	Disabled Rules:---17347
	Total Rules:------24414
No IP Blacklist Changes

Done
########pp.conf
version=0.7.1
snort_version=2.9.7.3
rule_url=https://www.snort.org/reg-rules/|snortrules-snapshot-2973.tar.gz|<OINKCODE_WAS_HERE>

ips_policy=balanced
ignore=deleted,experimental,local,decoder,preprocessor,sensitive-data

temp_path=/tmp
sid_changelog=/home/shepp/snort/var/log/sid_changes.log
rule_path=/home/shepp/snort/rules/snort.rules
sid_msg=/home/shepp/snort/sid-msg.map
sid_msg_version=1
