### ISSUE TITLE
error: uninitialized value $md5 - causes fail on ETPro rules

### ISSUE THREAD

**Issue by sempersecurus** [shirkdog/pulledpork#196]
Invoking pulledpork v0.7.1 as follows:
/home/snortscan/snort_src/pulledpork-read-only/pulledpork.pl -c /etc/snort/pulledpork.conf -l -w
++++++++++++++++++++++++++++++++++++
Checking latest MD5 for etpro.rules.tar.gz....
Use of uninitialized value $md5 in scalar chomp at /home/snortscan/snort_src/pulledpork-read-only/pulledpork.pl line 489.
Use of uninitialized value $md5 in pattern match (m//) at /home/snortscan/snort_src/pulledpork-read-only/pulledpork.pl line 491.
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
++++++++++++++++++++++++++++++++++++
That just keeps looping over and over.

**Comment by sempersecurus** [comment]
Similar errors using master branch 0.7.2:
Use of uninitialized value $md5 in scalar chomp at /home/snortscan/snort_src/pulledpork-read-only/pulledpork.pl line 522.
Use of uninitialized value $md5 in pattern match (m//) at /home/snortscan/snort_src/pulledpork-read-only/pulledpork.pl line 524.

**Comment by shirkdog** [comment]
This is a loop that I will be using the actual ET Pro set to test, with "-d" it should not care about the MD5 file, but it just keeps looping through.

**Comment by shirkdog** [comment]
So there is an issue on the ETPro side, where even if the API key is wrong, it still returns an HTTP 200, and pulledpork is built on HTTP error codes when things are broke.

Once this has been addressed, I will close out this issue.

**Comment by shirkdog** [comment]
Closing for now, reopen as necessary.
