### ISSUE TITLE
pulledpork stopped downloading snortrules

### ISSUE THREAD

**Issue by ecastel6** [shirkdog/pulledpork#203]
Hi, 
Today I noticed pulledpork was failing to download snortrules. It throws the error 

`Checking latest MD5 for snortrules-snapshot-2975.tar.gz....
        Error 422 when fetching https://www.snort.org/rules/snortrules-snapshot-2975.tar.gz.md5 at /usr/local/bin/pulledpork.pl line 517.
        main::md5file("4dc059f112442cb0049d80955454ad5422135b4a", "snortrules-snapshot-2975.tar.gz", "/tmp/", "https://www.snort.org/rules/") called at /usr/local/bin/pulledpork.pl line 1968
`
Commenting out the line for snortrules works ok. 
rule_url=https://www.snort.org/reg-rules/|snortrules-snapshot.tar.gz|<myactualoinkcode>

Snort version: 2.9.7.5 
Pulledpork: 0.7.2 
OS: Debian 8

Any tip?

**Comment by finchy** [comment]
That means the version of ruleset you are trying to download no longer exists because it has Eol'ed (error 422). 

[eol policy](http://www.snort.org/eol)

**Comment by ecastel6** [comment]
Hello Joel 

Thanks for your answer. That's what I guessed so Snort upgrade is a must.

Regards, 
Emilio

**Comment by finchy** [comment]
Correct sir.  This issue can be closed.
