### ISSUE TITLE
ERROR: Unable open rules

### ISSUE THREAD

**Issue by M3nin0** [shirkdog/pulledpork#207]
I 'm configuring Pulledpork and He has this problem:
ERROR: /etc/snort//snort.rules(0) Unable to open rules file "/etc/snort//snort.rules": No such file or directory.

How do I change this path where he is looking for the file

Thanks for all =D

**Comment by finchy** [comment]
You need to change the RULE_PATH variable in the snort.conf

**Comment by M3nin0** [comment]
The problem was in the position where was the $RULE_PATH repaired putting on line 549.


Thanks for help
