### ISSUE TITLE
snort ruleset md5 location has changed?

### ISSUE THREAD

**Issue by t1ck3ts** [shirkdog/pulledpork#208]
`Checking latest MD5 for snortrules-snapshot-2976.tar.gz....
        Error 501 when fetching https://www.snort.org/rules/snortrules-snapshot-2976.tar.gz.md5 at /usr/local/bin/pulledpork.pl line 517.
        main::md5file('xxxxxxxxxxxxxxxxxxxxx', 'snortrules-snapshot-2976.tar.gz', '/tmp/', 'https://www.snort.org/rules/') called at /usr/local/b
`

md5's now reside in `https://www.snort.org/downloads/registered/md5s`

have i missed anything?

**Comment by t1ck3ts** [comment]
diving deeper into logs, seems i didn't have some dependencies installed

**Comment by marcindulak** [comment]
Similar issue on CentOS7 https://github.com/shirkdog/pulledpork/issues/221
