### ISSUE TITLE
Feature Request: Need a way to leverage no_proxy environment variable

### ISSUE THREAD

**Issue by digitalebola** [shirkdog/pulledpork#213]
With the latest updates the proxy settings work great however I have a need to access an update server on my internal network and on the outside network.  the no_proxy environment variable is set on my host but is not leveraged by pulled pork.

My current work around (since I am not much of a coder) is to have two versions of pulledpork.pl. One is as written and the other has lines 1844-1896 commented out to avoid the proxy.

It would be nice to have PP read from the environment or offer a no_proxy option in the config.

**Comment by shirkdog** [comment]
See if this change fixes your issue:

index 8a2caaf..46b3ab3 100755
--- a/pulledpork.pl
+++ b/pulledpork.pl
@@ -44,6 +44,8 @@ use Data::Dumper;
 my ( $oinkcode, $temp_path, $rule_file, $Syslogging );
 my $VERSION = "PulledPork v0.7.2 - E.Coli in your water bottle!";
 my $ua      = LWP::UserAgent->new;
+#Read in proxy settings from the environment
+$ua->env_proxy;
 
 # for certificate validation, check for the operating system
 # and set the path to the certificate store if required.

**Comment by digitalebola** [comment]
This appears to have resolved the issue!  Thanks!
