### ISSUE TITLE
modifysid.conf is ignored/errored with new version

### ISSUE THREAD

**Issue by jcrochon** [shirkdog/pulledpork#215]
#This rule is enabled and it is unchanged:
2018012 "\$HOME_NET" "$ACCC_NET";

#Update deprecated threshold to detection_filter - jcrochon 07/14/2014
#has been working before the newest commit 6b6cf92f49a38aaca428d4eed208ab63f39ff169
#not sure which commit I had used before, but it has been a while, probably 6 months ago
\* "threshold:\s*\w+\s\w+\s*," "detection_filter:";

#This rule is enabled and it is unchanged:
2009098,2009099,2009966,2009967,2009968,2009969,2009970,2009972,2010008,2010139,2010140,2010141,2010142,2010143,2010144,2011699,2011700,2011701,2011702,2011703,2011704,2011705,2011706,2011707,2011710,2011711,2011712,2011713,2012247,2012467,2014459,2014734,2018012 "\$HOME_NET" "$ACCC_NET";

**Comment by shirkdog** [comment]
You have to provide the command line flag pointing to the modified.conf, or define it in the pulledpork.conf.

Can you provide the specific files and options you are using? Those changes you referenced in 6b6cf92 were mostly cosmetic.

**Comment by jcrochon** [comment]
/usr/local/bin/pulledpork.pl -M /etc/snort/modifysid.conf -vvEPc /etc/snort/pulledpork.conf @> pulledpork.log

modifysid=/etc/snort/modifysid.conf

**Comment by jcrochon** [comment]
Commit 1d98257d55afd63d0bdc195f7351bba617639484 works on modifysid.conf as expected. I'll keep trying the commits until I find the one it stops working as expected.

**Comment by jcrochon** [comment]
Commit 8b9441aeeb7e1477e5be415f27dbc4eb25dd9d59 works on modifysid.conf

**Comment by jcrochon** [comment]
Commit fdd60fe54c3706e1043df85735f82a5f71796868 works on modifysid.conf

**Comment by jcrochon** [comment]
Broken: commit 78cd7cd032717e5f2bc387104badde8c3358782b does not  work on modifysid.conf

**Comment by jcrochon** [comment]
Commit ea8b7776e86140e68a91943e62f585a2ed4d0867 works on modifysid.conf

**Comment by jcrochon** [comment]
modifysid.conf is first broken on commit 5d3a6b6359bfb09038bb2713bebe9099fbaf4f54

**Comment by jcrochon** [comment]
I will submit the fix to the latest commit.
