### ISSUE TITLE
Failed to parse !$HOME_NET

### ISSUE THREAD

**Issue by mindph** [shirkdog/pulledpork#218]
An error occurred: ERROR: /etc/snort/snort-global.conf(49) Failed to parse the IP address: !$HOME_NET.

The line in the snort config looks like this:
#Set up the external network addresses. Leave as "any" in most situations
#ipvar EXTERNAL_NET any
ipvar EXTERNAL_NET !$HOME_NET

**Comment by shirkdog** [comment]
do you have HOME_NET set in your snort.conf?

This is in Snort, not specifically in pulledpork.

**Comment by mindph** [comment]
Yes, the problem is I have a config for each interface where I am listening on and a global config that apply for all interfaces (since preproc and rule directories and so on are always the same).
The interface-specific configs define a $HOME_NET variable for each interface's network. So like snort-br0.conf is used by a snort process that sniffs on br0 with it's own attached network lets say its $HOME_NET=192.168.200.0/24 next the snort-br0.conf includes snort-global.conf for all other settings. Now since I have no clue what pulledpork does with the snort.conf I used the global one here and there it fails parsing $HOME_NET

**Comment by shirkdog** [comment]
Verify you have HOME_NET set to something in your configs, as this is not a pulledpork issue:
ipvar HOME_NET=192.168.200.0/24 
and not 
$HOME_NET=192.168.200.0/24

Reopen this if you find an issue specific to pulledpork.
