### ISSUE TITLE
rule download always yields 501 error on Centos7

### ISSUE THREAD

**Issue by ristov** [shirkdog/pulledpork#221]
I am using pulledpork-0.7.2 with two download URLs in pulledpork.conf (identical to the URLs in pulledpork.conf from the Pulledpork distribution):

rule_url=https://snort.org/downloads/community/|community-rules.tar.gz|Community
rule_url=https://rules.emergingthreats.net/|emerging.rules.tar.gz|open-nogpl

When running pulledpork with these URLs, I am getting the following errors:

Rules tarball download of community-rules.tar.gz....
    Error 501 when fetching community-rules.tar.gz at /usr/local/bin/pulledpork.pl line 469.
    main::rulefetch('Community', 'community-rules.tar.gz', '/tmp/', 'https://snort.org/downloads/community/') called at /usr/local/bin/pulledpork.pl line 1985

Checking latest MD5 for emerging.rules.tar.gz....
    Error 501 when fetching https://rules.emergingthreats.net/open-nogpl/snort-2.9.8/emerging.rules.tar.gz.md5 at /usr/local/bin/pulledpork.pl line 524.
    main::md5file('open-nogpl', 'emerging.rules.tar.gz', '/tmp/', 'https://rules.emergingthreats.net/open-nogpl/snort-2.9.8/') called at /usr/local/bin/pulledpork.pl line 1976

The files that Pulledpork fails to download are actually available. I am running Pullepork with direct access to Internet without any proxies. All packages on my Centos7 installation are properly updated. Also, pulledpork-0.7.0 works without any issues for me. If 0.7.0 is a stable version that is known to work on all platforms, I would suggest making it available under the Releases section.

**Comment by ristov** [comment]
...after changing the download URL for emergingthreats from https to http, the rule download works: 
rule_url=http://rules.emergingthreats.net/|emerging.rules.tar.gz|open-nogpl
I also verified that on the current node, pulledpork-0.7.0 doesn't work either with https downloads (works on my other centos7 boxes, though, which reside behind a proxy).

**Comment by shirkdog** [comment]
I am looking to 0.7.2 to be a stable release, so if this works in 0.7.2, we can close out the issue.

**Comment by shirkdog** [comment]
Cleanup of issues, if this is still happening, please reopen this issue.

**Comment by marcindulak** [comment]
501 was maybe due to perl-LWP-Protocol-https not installed?

**Comment by ristov** [comment]
This package was indeed missing and everything started to work after it was installed.Thanks for letting me know! 

    On Tuesday, November 8, 2016 2:43 PM, marcindulak <notifications@github.com> wrote:
 

 501 was maybe due to perl-LWP-Protocol-https not installed?—

**Comment by slesru** [comment]
Hello! Trying to install pulledpork on current centos 7 and got the same problem:

Checking latest MD5 for community-rules.tar.gz....
	Fetching md5sum for: community-rules.tar.gz.md5
** GET https://snort.org/downloads/community/community-rules.tar.gz.md5 ==> 501 Not Implemented
Error downloading https://snort.org/downloads/community/community-rules.tar.gz.md5: 501 Not Implemented [ 501 ]

This is
pulledpork -V
PulledPork v0.7.3 

And I use it over proxy, and run it as 
 /usr/bin/pulledpork -c /etc/pulledpork/pulledpork.conf -I balanced -P -W -v


Unfortunately, I can't test direct access on this host.

perl-LWP-Protocol-https is installed.

Thank you!
