### ISSUE TITLE
Does this replace the google code project?

### ISSUE THREAD

**Issue by clintharris** [shirkdog/pulledpork#222]
Apologies for what might be a dumb question...

Does this repo replace the [project](https://code.google.com/archive/p/pulledpork/) on Google Code?

**Comment by shirkdog** [comment]
Yes, the Google Code site is just an archive site for Pulledpork. New updates are being managed here on github. Anything that is a bug, or a new feature that you would like to be added, submit here, or send a pull request with your proposed changes.
