### ISSUE TITLE
MD5 Sum Returns 404

### ISSUE THREAD

**Issue by rossimo** [shirkdog/pulledpork#223]
```
    https://github.com/shirkdog/pulledpork
      _____ ____
     `----,\    )
      `--==\\  /    PulledPork v0.7.2 - E.Coli in your water bottle!
       `--==\\/
     .-~~~~-.Y|\\_  Copyright (C) 2009-2015 JJ Cummings
  @_/        /  66\_  cummingsj@gmail.com
    |    \   \   _(")
     \   /-| ||'--'  Rules give me wings!
      \_\  \_\\

Checking latest MD5 for snortrules-snapshot-2976.tar.gz....
	They Match
	Done!
Checking latest MD5 for community-rules.tar.gz....
	A 404 error occurred, please verify your filenames and urls for your tarball!
	Error 404 when fetching https://s3.amazonaws.com/snort-org/www/rules/community/community-rules.tar.gz.md5 at /etc/snort/pulledpork/pulledpork.pl line 505
	main::md5file('Community', 'community-rules.tar.gz', '/tmp/', 'https://s3.amazonaws.com/snort-org/www/rules/community/') called at /etc/snort/pulledpork/pulledpork.pl line 1926
```

**Comment by finchy** [comment]
This isn't an issue with Pulledpork.  This is a snort.org issue.  Looking into it.

**Comment by rossimo** [comment]
One reason I reported it here is that the 404 error seams to break the 0.7.2 release of pulledpork. It's spawned multiple pulledpork processes, which eat the CPU. Eventually came here after tracking down a pegged CPU issue.

**Comment by rossimo** [comment]
Could be an issue with how I fire up the script.

**Comment by shirkdog** [comment]
If this is not an issue with the URL, we can close this out, but rossimo what is causing a CPU spike?

**Comment by rossimo** [comment]
There were many pulledporked.pl instances running when I logged into the machine. I fire PulledPork via cron every few hours, and I haven't seen this issue until now.

**Comment by finchy** [comment]
Can you put a lock on the process in your crontab?

**Comment by DigiEbola** [comment]
MD5s at Snort.org were centralized to https://www.snort.org/downloads/snort/md5s and that broke things. Should be a easy fix.

**Comment by finchy** [comment]
No, those are for the packages, not for the rulesets.

**Comment by DigiEbola** [comment]
Weird, I was seeing 404's on the *.md5 files

**Comment by finchy** [comment]
Are you seeing them now?  Can you replicate the issue?

**Comment by DigiEbola** [comment]
I haven't tried... due to various distractions and the notion of a rewrite. The *.md5 files are back and the md5s file contains as follows: 

  76a96867d88663d2080bdcc98539ee31 community-rules.tar.gz
  40ecff7f156dbb95d0507218b584c150 opensource.tar.gz

**Comment by finchy** [comment]
I haven't heard any other complaints to the site, so let's consider this matter solved, for now.

**Comment by sac14** [comment]
I am also facing the same error.

So, whats the solution to it.

@finchy I did NOT get why the thread got closed. Plz help.

**Comment by sac14** [comment]
@finchy AND @rossimo 

i was stuck at this error since long, got the solution from this blog
http://blog.snort.org/2015/10/are-you-getting-404-errors-attempting.html

SOLUTION STEPS:
leafpad /etc/snort/pulledpork.conf

FIND AND REPLACE THIS LINE (AT line#21)
rule_url=https://s3.amazonaws.com/snort-org/www/rules/community/|community-rules.tar.gz|Community


WITH THIS ONE
rule_url=https://snort.org/downloads/community/|community-rules.tar.gz|Community

SAVE & EXIT
RUN THE PULLEDPORK COMMAND, YOU ARE GOOD TO GO

**Comment by dods2** [comment]
Try this https://blog.snort.org/2015/10/are-you-getting-404-errors-attempting.html
