### ISSUE TITLE
Snort binary does not exist.

### ISSUE THREAD

**Issue by lcarter419** [shirkdog/pulledpork#229]
I am a complete rookie at this, but followed the directions for installing PulledPork carefully. I got done and then ran perl d:\winids\pulledpork\pulledpork.pl -c d:\winids\pulledpork\etc\pulledpork.conf -T.

I got the following:  'uname' is not recognized as an internal or external command, operable program or batch file.  The specified Snort binary does not exist!  Please correct the value or specify the FULL rules tarball name in the pulledpork.conf!  
    at d:\winids\pulledpork\pulledpork.pl line 1932

I have no idea what to do now.  Please help!
lcarter419

**Comment by shirkdog** [comment]
You have to pass in the -p value to where the Snort binary is.

Also, running Snort and PulledPork on Windows is not a great idea, unless you are just messing around or learning how things work. There may be some issues that if they are in fact bugs in pulledpork, you can add them as additional issues.
