### ISSUE TITLE
How to get .conf ALPHA?

### ISSUE THREAD

**Issue by Alex-VM** [shirkdog/pulledpork#230]
I get an error saying I'm not using the current version of pulledpork.conf, that I should use the version shipped with PulledPork v0.7.2 - ALPHA. This is weird, because I installed pulledpork yesterday, and the conf file says the version is 0.7.2. Is it the ALPHA thing? Thanks

**Comment by shirkdog** [comment]
ALPHA is just a string added to the "$VERSION" variable in the pulledpork script. It is not included with this check of the pulledpork.conf file. 

You need to run pulledpork with -vvv and provide the command line you using and the output of the errors (minus your oinkcode).
