### ISSUE TITLE
Rule merging question

### ISSUE THREAD

**Issue by DigiAngel** [shirkdog/pulledpork#235]
So...per the docs:
~~~
# If you are running any rules in your local.rules file, we need to
# know about them to properly build a sid-msg.map that will contain your
# local.rules metadata (msg) information.  You can specify other rules
# files that are local to your system here by adding a comma and more paths...
# remember that the FULL path must be specified for EACH value.
# local_rules=/path/to/these.rules,/path/to/those.rules
local_rules=/usr/local/etc/snort/rules/local.rules
~~~

My understanding that items in the local_rules variable were not merged into the full snort.rules file, however this is what I'm seeing...is that by design?  Thank you.

**Comment by shirkdog** [comment]
This appears to be the case on a test run, let me look at the "design" and see if this is correct.

**Comment by DigiAngel** [comment]
Thankies :)

**Comment by dougburks** [comment]
In my testing, it appears that this behavior has changed between PulledPork 0.7.0 and the current 0.7.3 in github.  0.7.0 does not copy local.rules to downloaded.rules, but 0.7.3 does.

**Comment by DigiAngel** [comment]
Ok cool...thanks Doug for the validation...I like how 0.7.3 works.

**Comment by shirkdog** [comment]
The idea is to have local rules and merge everything into a single snort/suricata rule file.  If everyone likes this, we can close the issue.

**Comment by DigiAngel** [comment]
You're the boss shirkdog...I'll close it since I opened it :)
