### ISSUE TITLE
Error 422 

### ISSUE THREAD

**Issue by servebeer** [shirkdog/pulledpork#236]
Hello,
I am new to pulled-work, so I am probably overlooking something simple. I downloaded the latest version and modified the pulled-work.conf file to suite my environment. When I run pulled-work via "sudo pulledpork.pl -c /etc/snort/pulledpork.conf", I get the following error:

Error 422 when fetching https://www.snort.org/reg-rules/snortrules-snapshot-2970.tar.gz.md5 at /usr/sbin/pulledpork.pl line 534.
	main::md5file("419052bb1723b33aab7061b583c71982b6cae477", "snortrules-snapshot-2970.tar.gz", "/tmp/", "https://www.snort.org/reg-rules/") called at /usr/sbin/pulledpork.pl line 2007

Sincerely,
Jon

**Comment by finchy** [comment]
Dear (Name),

The version of rules you are attempting to download doesn't exist anymore as a result of our EOL policy.

Please see it here:
https://www.snort.org/eol

**Comment by finchy** [comment]
Oh boo. It's my generic response,  but still true.

**Comment by servebeer** [comment]
Hi Finchy,
I guess I don't understand what I am doing wrong. This is a new install and I am simply running this command:
pulledpork.pl -c /etc/snort/pulledpork.conf

I have reviewed my pulled-work.conf file and I don't see anywhere to set the version to download. I was assuming it would just grab the latest. How can I modify my config file so it always downloads the latest rules?

Thanks!
Jon

**Comment by servebeer** [comment]
So I tried the pulledpork script with cli switches instead of just the config file.

sudo pulledpork.pl -c /etc/snort/pulledpork.conf -u http://www.snort.org/reg-rules/snortrules-snapshot-2983.tar.gz

and now I get this error:  

You need to define an oinkcode, please review the rule_url section of the pulledpork config file!
 at /usr/sbin/pulledpork.pl line 1956.

So I try to manually add it on the cli too:

sudo pulledpork.pl -c /etc/snort/pulledpork.conf -u http://www.snort.org/reg-rules/snortrules-snapshot-2983.tar.gz -O MyOinkCode

but I still get the same error. Something must be wrong with the pulledpork.conf file. I have attached it to the post. 

Thanks!
Jon
[pulledpork.conf.txt](https://github.com/shirkdog/pulledpork/files/601715/pulledpork.conf.txt)
