### ISSUE TITLE
 Error 400 when fetching rules via proxy

### ISSUE THREAD

**Issue by thomaspries** [shirkdog/pulledpork#252]
Hi,

I try to fetch the rules via our proxy and I am using: 

sudo /usr/local/bin/pulledpork.pl -c /etc/snort/pulledpork.conf -l -vv

the verbose output shows, that pulledpork ( v0.7.3) got the correct proxy uri, but fetching fails with:

Checking latest MD5 for snortrules-snapshot-2990.tar.gz....
        Fetching md5sum for: snortrules-snapshot-2990.tar.gz.md5
** CONNECT https://www.snort.org/reg-rules/snortrules-snapshot-2990.tar.gz.md5/123456789 
==> 400 Bad Request 
        Error 400 when fetching https://www.snort.org/reg-rules/snortrules-snapshot-2990.tar.gz.md5 
at /usr/local/bin/pulledpork.pl line 534.
        main::md5file("123456789", "snortrules-snapshot-2990.tar.gz", "/tmp/", "https://www.snort.org/reg-rules/") called at /usr/local/bin/pulledpork.pl line 2007

When I try to get https://www.snort.org/reg-rules/snortrules-snapshot-2990.tar.gz.md5/123456789 via wget from the console, it works fine. 

I found https://code.google.com/archive/p/pulledpork/issues/174 but my proxy says "CONNECT www.snort.org:443", that looks good for me.

Thanks in advance.
Thomas

**Comment by slesru** [comment]
I have absolutely the same problem , proxy is squid 3.5.24.
And I can successfully download this md5 file using wget and the same proxy....

**Comment by shirkdog** [comment]
Have you tried the -W flag? This was added when there were some issues previously with various proxying and LWP.

**Comment by slesru** [comment]
-W solved problem.
Thank you very much!

**Comment by shirkdog** [comment]
Okay closing this out if there are no more issues...

**Comment by debernal** [comment]
Hi, I´m having this issue, where exactly do I have to add the -W? rule-update -W returned the same 400 error. Thanks.

**Comment by franckygos** [comment]
I had the same issue with security onion, I resolved the problem like this :

The pulledpork.pl script is launch with the sguill account.
I had a .bashrc and .bash_profile with the proxy settings

$cat ~/.bashrc 
export http_proxy="http://myip:8080/"
export https_proxy="http://myip:8080/"

$cat ~/.bash_profile
if [ -f ~/.bashrc ];then
    . ~/.bashrc
fi

The 2 key points are :
- The proxy settings must finish with a slash
- The https settings must use  http protocol (no "s" behind = )
