### ISSUE TITLE
pulledpork doesnt work with confined selinux user privileges

### ISSUE THREAD

**Issue by ghost** [shirkdog/pulledpork#254]
A user with user_u privileges can't update the rulesets. However, performing the same task (with the same user) using oinkmaster works. If i alter the user privileges to eg unconfined_u it works.

I had setup the confined user's crontab to periodically download rulesets, etc 

Wondering does the downloading of rulesets alter  the pulledpork excecutable in /usr/bin/pulledpork?

**Comment by shirkdog** [comment]
You will need to provide the specific use case where pulledpork is failing for you, including the way oinkmaster is working but pulledpork does not. Nothing in pulledpork should be the cause of a permission issue, only something in the local environment.

**Comment by shirkdog** [comment]
Reopen if this is still occurring, as the script is known to work, but if there is an issue with the RPM, documenting it here will help.
