### ISSUE TITLE
Set up a local mirrror?

### ISSUE THREAD

**Issue by jsilverman-blispay** [shirkdog/pulledpork#256]
I've looked all over the interwebs for this but can't find anything.

Is there some way to set up a local rules mirror and point Pulledpork to that?

I looked through PP's code and it seems likethis may work:
* download the files listed in "rule_url" directives in pulledpork.conf
* also download their associated MD5 files
* serve them on a local webserver
* configure pp with the local mirror URLs in "rule_url" directives

But in looking at pp's code I found that pp has *hard coded* the values of the various snort.org rules mirrors in order to do testing and MD5 checksumming. I feel like there are some non-obvious details that I'm missing.

Finally, in trying to set this up on my own, I got "reported for abuse" during local tests of my mirror, as I download rulesets too quickly. This does make building and testing a local mirror with no documentation a bit difficult.

Please advise. Even a link to a doc explaining this will be great.

Thanks
JDS

**Comment by shirkdog** [comment]
Exactly what you have written should work, setup a "local" test system, with apache/nginx, with custom rule files in a tar.gz and md5 served up by the web server.

**Comment by shirkdog** [comment]
Closing, as I have ran a production setup like this for years.
