### ISSUE TITLE
Pulledpork should be able to download and process VRT rules for Suricata

### ISSUE THREAD

**Issue by stan-prescott** [shirkdog/pulledpork#265]
Talos does not have any rules specifically for Suricata. Makes sense, Talos rules are for Snort. However, Suricata can work with most Talos rules. Pulledpork lists as a feature that it will manage rules for Suricata but when the user enters suricata-3.2.1 as the snort version, it will download and process the ET and ET Pro rules just fine, but not the Talos VRT rules. Pulledpork attempts to place "suricata-321" in the snortrules-snapshot filename instead of the snort version which causes a failure in the download of the rules because there are no rules files by that name. If a feature of Pulledpork is to manage rules for Suricata, it should be able to download and process the Talos VRT rules.

**Comment by shirkdog** [comment]
Pulledpork "should" work with suricata and ET/ETPro rules. However there is no support for VRT rules to run on Suricata. A new tool has been released for managing suricata rules: 

[https://github.com/OISF/suricata-update](url)

One of the features is the rulesets that suricata-update will manage, so this might be a feature request there.
