### ISSUE TITLE
Continue after excessive rules download error.

### ISSUE THREAD

**Issue by jcrochon** [shirkdog/pulledpork#271]
I was testing too much and got temporarily blocked which crashes the whole script. I would like to be able to continue onto non-blocked sites, such as ET even when VRT is blocked or the site moves.
`Checking latest MD5 for snortrules-snapshot-2990.tar.gz....
        Error 429 when fetching https://www.snort.org/reg-rules/snortrules-snapshot-2990.tar.gz.md5 at /usr/local/bin/pulledpork.pl line 534.
        main::md5file("REDACTED", "snortrules-snapshot-2990.tar.gz", "/var/tmp/", "https://www.snort.org/reg-rules/") called at /usr/local/bin/pulledpork.pl line 2006`

**Comment by jcrochon** [comment]
I have added my suggested code and it tested well.
#272

**Comment by shirkdog** [comment]
#272 Handles this
