### ISSUE TITLE
Problems running pulledPork

### ISSUE THREAD

**Issue by nan008** [shirkdog/pulledpork#273]
Snort version 2.9.9.0
OS Centos 7.3
PulledPork version 7.3

I ma new to Snort and PulledPork. This is the first time I started both. I went to the pulledpork.conf and make changes as described in the notes

Getting those errors

```
Prepping rules from snortrules-snapshot-2990.tar.gz for work....
	extracting contents of /tmp/snortrules-snapshot-2990.tar.gz...
Invalid header block at offset unknown at /usr/local/bin/pulledpork.pl line 269.
```

```
Prepping rules from community-rules.tar.gz for work....
	extracting contents of /tmp/community-rules.tar.gz...
	Ignoring plaintext rules: deleted.rules
	Ignoring plaintext rules: experimental.rules
	Ignoring plaintext rules: local.rules
	Extracted: /tha_rules/Snort-Community-community.rules
Use of uninitialized value $Snort in regexp compilation at /usr/local/bin/pulledpork.pl line 317.
```

Anyone can tell me what should I do to correct it?

**Comment by shirkdog** [comment]
This should be the value of the Snort version you have to set in the conf, but reopen this issue if you are still having problems.

**Comment by saisora** [comment]
i have the same problem. 
"Use of uninitialized value $Snort in regexp compilation at /usr/local/bin/pulledpork.pl line 317."
