### ISSUE TITLE
New user on CentOS 7, just testing around with this error.

### ISSUE THREAD

**Issue by VBQL** [shirkdog/pulledpork#279]
The specified Snort binary does not exist!
Please correct the value or specify the FULL rules tarball name in the pulledpork.conf!
 at /usr/local/bin/pulledpork.pl line 1983.

I've basically copied the guide from https://linoxide.com/monitoring-2/install-configure-snort-ids-centos-6-x-7-x/ and replaced the <oinkcode> with the one I have, but it seems that it is not working.

**Comment by shirkdog** [comment]
Pulledpork tries to determine your snort version by running "snort -V". If you do not provide a Snort version, and the Snort binary is not available in your path, you will get that error. The setting in pulledpork.conf is 'snort_version'
