### ISSUE TITLE
Suricata needs SIGUSR2 to reload rules

### ISSUE THREAD

**Issue by edeca** [shirkdog/pulledpork#280]
As per the [documentation](http://suricata.readthedocs.io/en/latest/rule-management/rule-reload.html), Suricata uses SIGUSR2 to signal when rules must be loaded.  Sending SIGHUP is not effective.  SIGUSR2 is signal number 12.

A number of options are possible:

* Allow the user to specify a signal number as well as `-H`, though this would break if a user has Suricata (which expects USR2) and Barnyard (which expects HUP).
* The config format could change for a future version, allowing the user to specify pairs of PID file/signal.
* Modification could be made to function `sig_hup` to look for a string like `suricata` in the PID path and send an alternate signal.  Very hacky.

**Comment by aoshiken** [comment]
Just FYI, take a look to the explanation by Shirkdog at PR #274

**Comment by shirkdog** [comment]
Closing this, let me know if the updated code from the pull request and tweaks do not work.

**Comment by aoshiken** [comment]
Michael, IMHO the `README.md` file in the root folder deserves updating the `-H` option... :)

**Comment by shirkdog** [comment]
done.
