### ISSUE TITLE
Amazon Linux AMI issue

### ISSUE THREAD

**Issue by Devon21** [shirkdog/pulledpork#281]
I'm getting this error when I run it. Please let me know what I can do. 

Use of uninitialized value $Value in pattern match (m//) at /usr/local/bin/pulledpork.pl line 149, <CONFIG> line 131.

pulledpork.conf:

    # Valid Distro Types:
    # Debian-6-0, Ubuntu-10-4
    # Ubuntu-12-04, Centos-5-4
       FC-12, FC-14, RHEL-5-5, RHEL-6-0
    # FreeBSD-8-1, FreeBSD-9-0, FreeBSD-10-0
    # OpenBSD-5-2, OpenBSD-5-3
    # OpenSUSE-11-4, OpenSUSE-12-1
    # Slackware-13-1
    #distro=FreeBSD-8-1

**Comment by shirkdog** [comment]
You have to set the distro to something, which depends on the AMI you are using. You either set it in the pulledpork.conf file, or with the following command line flag:
```  
     -D What Distro are you running on, for the so_rules
      For latest supported options see 
      http://www.snort.org/snort-rules/shared-object-rules
      Valid Distro Types:
		Debian-6-0, Ubuntu-10-4, Ubuntu-12-04, Centos-5-4
		FC-12, FC-14, RHEL-5-5, RHEL-6-0
		FreeBSD-8-1, FreeBSD-9-0, FreeBSD-10-0, OpenBSD-5-2, OpenBSD-5-3
		OpenSUSE-11-4, OpenSUSE-12-1, Slackware-13-1
```
Basically match the latest version of the Linux distro you are using, which will pull in the appropriate precompiled shared object rules.

**Comment by Devon21** [comment]
Perfect Thank you... DOH on my part :)
