### ISSUE TITLE
pulledpork and colon within in msg-text

### ISSUE THREAD

**Issue by rgctoo** [shirkdog/pulledpork#283]
Neither snort nor baryard2 complain a colon within the msg-text.
It's a pulledpork flea!

--- 8< -- snort manueal -- >8 ---
 3.4.1 msg

The msg rule option tells the logging and alerting engine the message to print along with a packet dump or to an alert. It is a simple text string that utilizes the \ as an escape character to indicate a discrete character that might otherwise confuse Snort's rules parser (such as the semi-colon ; character).

3.4.1.1 Format

    msg:"<message text>";
--- 8< ----------------------- >8 ---
Am 13.03.2017 um 01:53 schrieb Joel Esler (jesler):
> Manual.snort.org <http://Manual.snort.org>
>
> http://manual-snort-org.s3-website-us-east-1.amazonaws.com/node31.html#SECTION00441000000000000000
>
> -- 
> Sent from my iPhone
>
> On Mar 12, 2017, at 20:30, Claus Regelmann <rgc@rgc1.inka.de <mailto:rgc@rgc1.inka.de>> wrote:
>
>> Where are these restictions documented ??
>>
>> Am 10.03.2017 um 23:15 schrieb Joel Esler (jesler):
>>> You should not use colons, backslashes, backticks, or semi colons in the rule msg.
>>>
>>> -- 
>>> Sent from my iPhone
>>>
>>>> On Mar 10, 2017, at 16:39, Claus Regelmann <rgc@rgc1.inka.de <mailto:rgc@rgc1.inka.de>> wrote:
>>>>
>>>> Hello,
>>>>
>>>> pulledpork also generates a file 'sid-msg.map' that maps the sid of a rule to its msg-text.
>>>> And other programs, e.g. barnyard2, rely on this file.
>>>>
>>>> If the msg-text of a rule contains a colon, the corresponding text in sid-msg.map is truncated just before the colon.
>>>> Is ':' a forbidden character in the 'quoted' message text? I never read about, and snort never complained about.
>>>>
>>>> My perl know how is very low, but i think the 'split' in the marked line below causes the problem.
>>>> ---8<-- pulledpork.pl -->8---
>>>> ...
>>>>            my @optarray = split( /(?<!\\);\s*/, $options ) if $options;
>>>>            foreach my $option ( reverse(@optarray) ) {
>>>>>>>>>>>>>>>   my ( $kw, $arg ) = split( /:\s*/, $option ) if $option; <<<<<<<<<<<<
>>>>       my $gid = $k;
>>>>       $gid = 1 if $k == 0;
>>>> ...
>>>> ---8<------------------->8---
>>>> This ':'-split on the rule's text is to simple. It ignores the quotes around the 'msg:' part.
>>>>
>>>> Is there a friendly perl specialist to fix the problem ??
>>>>
>>>> Regards
>>>> Claus
>>>>
>>>>
>>>>
>>>>
>>>>
>>>>
>>>>
>>>>
>>>> ------------------------------------------------------------------------------
>>>> Announcing the Oxford Dictionaries API! The API offers world-renowned
>>>> dictionary content that is easy and intuitive to access. Sign up for an
>>>> account today to start using our lexical data to power your apps and
>>>> projects. Get started today and enter our developer competition.
>>>> http://sdm.link/oxford
>>>> _______________________________________________
>>>> Snort-users mailing list
>>>> Snort-users@lists.sourceforge.net <mailto:Snort-users@lists.sourceforge.net>
>>>> Go to this URL to change user options or unsubscribe:
>>>> https://lists.sourceforge.net/lists/listinfo/snort-users
>>>> Snort-users list archive:
>>>> http://sourceforge.net/mailarchive/forum.php?forum_name=snort-users
>>>>
>>>> Please visit http://blog.snort.org to stay current on all the latest Snort news!
>>>
>>

**Comment by shirkdog** [comment]
What Joel said is how I would interpret the use of a colon, it should never be used in a msg field. If anything, pulledpork should generate an alert and state this is bad rule style writing.

**Comment by rgctoo** [comment]
I do not agree with Joel's opinion! The msg text is a quoted string and, as I said before,
neither Snort nor Suricata nor Barnyard2 complain colons in the msg text.
Nor is this restriction documented in the manuals (Snort, Suricata).
So this restriction must be imposed by pulledpork, isn't it?
I tried to locate the bug, and I found it. But my perl knowledge is to low to correct it.
Please be so kind and correct this flea.

**Comment by shirkdog** [comment]
Right, so based on the "opinion" that is not documented, and the fact it only causes an issue with pulledpork, pulledpork must handle it, escape it properly for itself to not cause weird issues when applying PCRE rules.

**Comment by rgctoo** [comment]
It is your perl-code. It does not honor quoted strings!

**Comment by rgctoo** [comment]
As I said I've min perl KH. But
"foreach my $option ( **reverse**(@optarray) ) {"
tells me that you are

**Comment by rgctoo** [comment]
I patched pulledpork-0.7.3  to fit my demands:
---- allow colons et.al.  within msg-text when generating sid-msg.map
---- exclude local-(extra-) rules in "snort.rules"

xxx:/opt/snort/buildrules# cat pulledpork-0.7.3-cr.patch
--- pulledpork-0.7.3/pulledpork.pl    2017-12-07 16:13:06.000000000 +0100
+++ pulledpork.pl    2017-12-27 21:53:03.000000000 +0100
@@ -41,7 +41,7 @@

  # we are gonna need these!
  my ($oinkcode, $temp_path, $rule_file, $Syslogging);
-my $VERSION = "PulledPork v0.7.3";
+my $VERSION = "PulledPork v0.7.3cr";
  my $HUMOR   = "Making signature updates great again!";
  my $ua      = LWP::UserAgent->new;

@@ -635,13 +635,14 @@
      my ($hashref, $path, $extra_rules) = @_;
      my ($file, $sid, $gid, @elements);
      print "\t" if ($Verbose && !$Quiet);
-    print "Reading rules...\n" if !$Quiet;
+    print "Reading rules from path='$path', extra files='$extra_rules' ... \n" if !$Quiet;
      my $reading_old_rules = $path eq ($rule_file_path || '');
      my @local_rules = split(/,/, $extra_rules);
      foreach (@local_rules)
      {    #First let's read our local rules and assign a gid of 0
          $extra_rules = slash(0, $_);
          $file = basename($extra_rules);
+    print "\t... extra file '$extra_rules ...\n";
          if ($extra_rules && -f $extra_rules) {
              open(DATA, "$extra_rules")
                  || croak "Couldn't read $extra_rules - $!\n";
@@ -1223,7 +1224,9 @@
                      push(@{ $$sidhash{$gid}{$k2}{refs} }, trim($arg));
                  }
                  elsif ($kw eq "msg") {
-                    $arg =~ s/"//g;
+            $arg = $1 if ($options =~ /msg:\s*"([^"]*)/);
+            # print $options,"\n",$arg,"\n";
+                    #$arg =~ s/"//g;
                      $$sidhash{$gid}{$k2}{msg} = trim($arg);
                  }
                  elsif ($kw eq "rev") {
@@ -1325,10 +1328,11 @@
      print "Writing $file....\n" if !$Quiet;
      open(WRITE, '>', "$file") || croak "Unable to write $file - $!\n";

-    #if ( $gid == 1 ) {
+    #  if ( $gid == 1 ) {
      foreach my $fn (sort keys %$categories) {
          print WRITE "\n\n# ----- Begin $fn Rules Category ----- #\n";
          foreach my $gid (sort keys %{ $categories->{$fn} }) {
+        next if ($gid==0);
              print WRITE "\n# -- Begin GID:$gid Based Rules -- #\n\n";
              foreach my $sid (sort keys %{ $categories->{$fn}{$gid} }) {
                  next unless defined $$hashref{$gid}{$sid}{'rule'};
@@ -1344,6 +1348,7 @@
              }
          }
      }
+    # }
      close(WRITE);
      print "\tDone\n" if !$Quiet;
  }
@@ -1497,6 +1502,7 @@
                  $msg_holder =~ s/";//;
              }
              else { $msg_holder = "Unknown MSG" }
+            # print "... deleted $msg_holder\n";
              push(@delsids, "$msg_holder ($k1:$k2)");
              $dt++;
          }
@@ -2299,7 +2305,7 @@
          read_rules(\%oldrules_hash, "$rule_file_path", $local_rules);
      }

-    #print Dumper(%oldrules_hash);
+    # print Dumper(%oldrules_hash);
  }

  # Clean up temp path


Am 16.10.2017 um 22:04 schrieb Shirkdog:
