### ISSUE TITLE
modifysid.conf does not consider sid list

### ISSUE THREAD

**Issue by jcrochon** [shirkdog/pulledpork#291]
Cannot use a list of sids -- it will only modify the last sid in the list.
I have to use single lines to get the expected results.

I have tried: 

> 1:2009205,1:2009206,1:2009207,1:2009208 "1024:" "!3391,1024:"
and
> 1:2009205-1:2009208 "1024:" "!3391,1024:"

Only works this way:
> 1:2009205 "1024:" "!3391,1024:"
> 1:2009206 "1024:" "!3391,1024:"
> 1:2009207 "1024:" "!3391,1024:"
> 1:2009208 "1024:" "!3391,1024:"

**Comment by shirkdog** [comment]
Think that is functioning as designed...

**Comment by jcrochon** [comment]
Ah. I assumed the list format was either comma or dash. Thanks
