### ISSUE TITLE
Version 0.7.3 processing opensourse.gz using -nTP

### ISSUE THREAD

**Issue by mesteele101** [shirkdog/pulledpork#294]
I'm trying to process the existing rules and bypass processing the opensource.gz file. Pulledpork 0.7.2 works fine but 0.7.3 does not.

In 0.7.2 using -nTP processes the existing rules and **bypasses** the existing opensource.gz file

In 0.7.3 using -nTP processes the existing rules and **processes** the existing opensource.gz file

**Comment by shirkdog** [comment]
does the opensource.gz file exist?

**Comment by mesteele101** [comment]
Yes it exists and it processes which it shouldn’t.

 

Best regards,

Michael...

**Comment by shirkdog** [comment]
If you do not use -nTP, does 0.7.2 process the open source rules? I want to get at why that happened in 0.7.2, because the idea would be if you do not want to process a rule file, it should not be defined in "rule_path", regardless of the cli options.

**Comment by mesteele101** [comment]
Yes, 0.7.2 work.

 

Best regards,

Michael...

**Comment by shirkdog** [comment]
This seems to be an issue where 0.7.2 would not process an already existing opensource.gz when using the -nTP switch, but if the file is downloaded, pulledpork should process it. So I believe it was something that was broken in 0.7.2, but then fixed in 0.7.3, and was not the way you wanted it. There might be a way to always skip processing the opensource.gz file, but otherwise the workaround is to enable it and then remove it from your rule_path so it does not get included.

**Comment by mesteele101** [comment]
-n Do everything other than download of new files (disablesid, etc)

   -T Process text based rules files only, i.e. DO NOT process so_rules

   -P Process rules even if no new rules were downloaded

 

Using the abvove switches has ALWAYS bypassed processing the opensource.gz file, even pre 0.7.2.

 

If I change anything in one of Pullporks configuration files I’ll need to run PulledPork and process the rules only, not  the opensource.gz file.

 

Processing the rules tarball only takes about 30 seconds, and processing the opensource.gz file adds another 30-45 minutes.

 

Something was changed in the routine that processed the rules tarball bypassing the MD5 check (offline mode? -P).

 

When the –nTP switches are used we ONLY need to re-process the actual rules tarball, not the opensource.gz file. This is the way Pulledpork has always worked until 0.7.3

 

You can test it very easily. Just drop whichever .pl file you want to test in the root folder.

 

Best regards,

Michael...

**Comment by shirkdog** [comment]
> Processing the rules tarball only takes about 30 seconds, and processing the opensource.gz file adds another 30-45 minutes.
That is terrible, I tested and this takes 5 seconds on my laptop (quad core, 32GB ram) to process the opensource.gz file...so if there are no objections, we can ensure opensource.gz is not processed when that combination of flags is used.

**Comment by mesteele101** [comment]
Perl processes the rules tarball in just a few seconds, but perl has always been extremely SLOW processing the opensource.gz file. I'm on Windows so Perl may operate differently. If I manually use untar, it only take a few seconds to process the opensource.gz file.

Changing any one of the configuration files in the etc folder requires PulledPork to re-process the rules. If you only want to process the changes with the existing rules tarball the -nTP switches was doing that. In that example there is no reason to touch the opensource.gz file. That is how it was working in all previous versions of PulledPork.

I did complain several times to Joe in the past and he was looking into it.

**Comment by vrtadmin** [comment]
the opensource.gz file doesn't get much simpler to process.  So, I don't think it's the file itself.

**Comment by mesteele101** [comment]
Perl is the bottleneck, at least in Windows. The problem still exists when the MD5 changes for the opensource.gz file.

 

Maybe there is a way to use something other than Perl  to dissolve?  I can manually untar the opensource file in just a few seconds.

 

When perl dissolves the opensource file it takes just as long to do the initial dissolve into an empty signatures folder, as it does to overwrite existing files. 

 

Best regards,

Michael...

**Comment by mesteele101** [comment]
Running 0.7.3 in windows line 707 gets an error. It appears that you have added a Unix command (grep) that is not compatible with Windows.

Prepping rules from opensource.gz for work....
        Done!
Reading rules...
Can't find Unicode property definition "u" in regex; marked by <-- HERE in m/^d:\winids\pu <-- HERE lledpork\temp/tha_rules/.$/ at d:\winids\pulledpork\pulledpork.pl line 707.
