### ISSUE TITLE
Detect or identify Snort 3

### ISSUE THREAD

**Issue by vrtadmin** [shirkdog/pulledpork#296]
Since Snort 3 and Snort 2's rulesets are different in structure, we'd want users to be able to specify, or automatic detection of the version of Snort the user is running and be able to handle the rules structure appropriately.

**Comment by shirkdog** [comment]
Current code will handle rule updates, but the edge cases will be handled in the 0.8.0 release.

**Comment by DigiAngel** [comment]
Before jumping into snort3, what's the status on this?  Thank you Shirkdog!

**Comment by finchy** [comment]
Snort 3 is supported as far as rule updates with 0.8.0.  Modifications to rules and such have to be tested.

**Comment by DigiAngel** [comment]
Beautiful thank you.

**Comment by finchy** [comment]
Closing this, as pulledpork work with Snort3 has shifted to pulledpork3
