### ISSUE TITLE
Process Snort 3 rules

### ISSUE THREAD

**Issue by vrtadmin** [shirkdog/pulledpork#297]
Since Snort 3's ruleset is different in structure, there is going to be a lot to look at in pulledpork to ensure compatibility to handle the different functions of pulledpork.  (Drop enablement, policy usage, suppression, commenting rules out, ignoring rules, etc.)

**Comment by DigiAngel** [comment]
Any status on this?

**Comment by finchy** [comment]
It should work with the older snortrules-snapshot structure, AFAIK.  PulledPork doesn't yet handle the light speed package.

**Comment by DigiAngel** [comment]
Ok cool...might have to just grep/sed/awk my way to freedom until this pans out :)

**Comment by DigiAngel** [comment]
This does not appear to be the case:

```
Checking latest MD5 for snortrules-snapshot-3140.tar.gz....
Error downloading https://www.snort.org/rules/snortrules-snapshot-3140.tar.gz.md5?oinkcode=<snip>: 422 Unprocessable Entity [ 422 ]

```

**Comment by finchy** [comment]
Closing this, as this work has shifted to pulledpork3
