### ISSUE TITLE
initialization error: 'use of uninitiallized $snort in regexp compilation (line 348)

### ISSUE THREAD

**Issue by footloosejava** [shirkdog/pulledpork#302]
From latest clone and running for first time.

OS: Linux (Debian - stable):

![image](https://user-images.githubusercontent.com/32090281/35548655-dee7031c-0535-11e8-8b33-717dd88722bc.png)

**Comment by shirkdog** [comment]
I might tie this to some of the "pulledpork is running for the first time" items that would be a nice to have, but I normally just create the directories and files up front before running.  Close this and tracking the general issues of missing files in #337
