### ISSUE TITLE
Centos 7 501 Not Implemented

### ISSUE THREAD

**Issue by slesru** [shirkdog/pulledpork#303]
Hello! 

There is the same issue, but it closed, so I creating new one.

Trying to install pulledpork on current centos 7 and got the same problem:

Checking latest MD5 for community-rules.tar.gz....
Fetching md5sum for: community-rules.tar.gz.md5
** GET https://snort.org/downloads/community/community-rules.tar.gz.md5 ==> 501 Not Implemented
Error downloading https://snort.org/downloads/community/community-rules.tar.gz.md5: 501 Not Implemented [ 501 ]

This is
pulledpork -V
PulledPork v0.7.3

And I use it over proxy, and run it as
/usr/bin/pulledpork -c /etc/pulledpork/pulledpork.conf -I balanced -P -W -v

Unfortunately, I can't test direct access on this host.

perl-LWP-Protocol-https is installed.

Thank you!

**Comment by shirkdog** [comment]
If this is still happening, please reopen with more detail.

**Comment by slesru** [comment]
Dunno, I use local mirror as workaround.
6 Feb 2018 was long time ago...

**Comment by shirkdog** [comment]
Actually I was able to cause this on a test build, I was missing the p5-LWP-Protocol-https pkg for FreeBSD. So either install it with epel, or install the modules yourself and see if that works for you.

**Comment by slesru** [comment]
It is already installed:

Package perl-LWP-Protocol-https-6.04-4.el7.noarch already installed and latest version.

Did not test if it works though..

Thank you!
