### ISSUE TITLE
Use of uninitialized value $arch in regexp compilation at /usr/local/bin/pulledpork.pl line 348.

### ISSUE THREAD

**Issue by PaulGuijt** [shirkdog/pulledpork#306]
PP running on my RasPi /w Debian Stretch reports me on a daily basis:

```
...
Prepping rules from emerging.rules.tar.gz for work....
Use of uninitialized value $arch in regexp compilation at /usr/local/bin/pulledpork.pl line 348.
...
	Done!
Prepping rules from snortrules-snapshot-29111.tar.gz for work....
Use of uninitialized value $arch in regexp compilation at /usr/local/bin/pulledpork.pl line 348.
...
```

How can I fix the problem causing "Use of uninitialized value $arch in regexp compilation at /usr/local/bin/pulledpork.pl line 348."?

**Comment by Abdirahman-Hish** [comment]
I am having the same issue.

**Comment by shirkdog** [comment]
At this time, there are no precompiled signatures for the ARM platform, so you can set the "distro" setting in your pulledpork.conf to ARM which will just do nothing, or use the "-T" command line argument to just process text rules.
