### ISSUE TITLE
pulledpork.conf "snort_version=" variable heads up ETPRO ruleset

### ISSUE THREAD

**Issue by samsonslice** [shirkdog/pulledpork#308]
I have been fighting an issue with pulledpork.pl trying to pull down my ETPRO ruleset. It kept throwing the following:
`
    https://github.com/shirkdog/pulledpork
      _____ ____
     `----,\    )
      `--==\\  /    PulledPork v0.7.3 - Making signature updates great again!
       `--==\\/
     .-~~~~-.Y|\\_  Copyright (C) 2009-2017 JJ Cummings, Michael Shirk
  @_/        /  66\_  and the PulledPork Team!
    |    \   \   _(")
     \   /-| ||'--'  Rules give me wings!
      \_\  \_\\
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Checking latest MD5 for etpro.rules.tar.gz....
Use of uninitialized value $md5 in scalar chomp at /usr/bin/pulledpork line 599.
Use of uninitialized value $md5 in pattern match (m//) at /usr/bin/pulledpork line 601.
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....
	No Match
	Done
Rules tarball download of etpro.rules.tar.gz....`

and would get stuck in an infinite loop. The issue SEEMS to be caused by having a version of suricata containing 2 decimals in the snort_version=suricata-X.X.X variable in pulledpork.conf such as "4.0.4".
ETPRO rules works fine so long as you only have 1 decimal in the version instead of 2 such as "4.0" . Might be ETPRO's side of things being really picky about the version format... Hope this helps anyone else running into the issue.

**Comment by samsonslice** [comment]
I guess I posted this here so maybe a comment could be added to the pulledpork.conf file warning about the version formatting issue with ETPRO ruleset

**Comment by shirkdog** [comment]
Yes, and it is bundled with suricata:
https://github.com/OISF/suricata-update

I added information to the pulledpork.conf and the README for anyone wanting to use pulledpork for suricata and ETPRO rules, but the preferred method for updating suricata is now their suricata-update script.

**Comment by shirkdog** [comment]
Think this is handled, closing, reopen if this is still not working.
