### ISSUE TITLE
Installing PulledPork on Raspbian: /etc/snort/rules/snort.rules not created

### ISSUE THREAD

**Issue by polleke67** [shirkdog/pulledpork#315]
1. Running snort-2.9.11.1 under Raspbian on a RP-1B+ fine. Configuration and rules checked okay (sudo snort -T -c /etc/snort/snort.conf -i eth0).
2. Installed pulledpork-0.7.3 successfully (/usr/local/bin/pulledpork.pl -V).
3. Edited /etc/snort/pulledpork.conf as described on https://sublimerobots.com/2017/01/snort-2-9-9-x-ubuntu-installing-pulledpork/
4. Executed pulledpork (sudo /usr/local/bin/pulledpork.pl -c /etc/snort/pulledpork.conf -l), but this time I got an error:
	Use of uninitialized value $arch in regexp compilation at /usr/local/bin/pulledpork.pl line 348
	Out of memory!
5. When executing the command again, all goes fine without an error msg, but /etc/snort/rules/snort.rules is NOT created.
6. Now we finally execute snort (sudo snort -T -c /etc/snort/snort.conf -i eth0)
	ERROR: /etc/snort//etc/snort/rules/snort.rules(0) Unable to open rules file "/etc/snort//etc/snort/rules/snort.rules": No such file or directory.
	Fatal Error, Quitting..

Any help please why /etc/snort/rules/snort.rules is not created .....

**Comment by shirkdog** [comment]
This was brought up in #141 and this is normally set by the user. In the case of arm, there are no precompiled shared object rules. I will close out #141 and add in something to automatically handle this when the architecture is NOT i386 or x86-64

**Comment by mcooper-veea** [comment]
@shirkdog - please do you know if there are any plans for precompiled shared object rules to be provided for arm?

**Comment by mcooper-veea** [comment]
> This was brought up in #141 and this is normally set by the user. In the case of arm, there are no precompiled shared object rules. I will close out #141 and add in something to automatically handle this when the architecture is NOT i386 or x86-64

@shirkdog - please do you know if there are any plans for precompiled shared object rules to be provided for arm?

**Comment by finchy** [comment]
PulledPork would not be the authoritative answer for this, @vrtadmin would be.  (and since that's me)..  no, we have no plans for creating Precomp for arm.

**Comment by mcooper-veea** [comment]
> PulledPork would not be the authoritative answer for this, @vrtadmin would be. (and since that's me).. no, we have no plans for creating Precomp for arm.

Thanks for the speedy response, even though it's a no to arm. I was planning to try Talos next, but you've saved me that job.
