### ISSUE TITLE
The first adviced command line doesn’t work

### ISSUE THREAD

**Issue by Azaretdodo** [shirkdog/pulledpork#316]
Hello,

Your first adviced command line give one error and one missing module !

I have this answer for a missing:

**_you may need to install the LWP::UserAgent module_**

where can I find this module ?

I have a pop up error answer at the end :

BEGIN failed--compilation aborted at ./pulledpork.pl line 24

Thank you in advance to repair my two problem,

Regards.

Dorian ROSSE.

**Comment by shirkdog** [comment]
You have several options, but normally you install the necessary perl modules from your OS distribution. The other option is to install them yourself from https://www.cpan.org/

**Comment by Azaretdodo** [comment]
I installed the pulledpork from the GitHub repositorie but It can’t works !

I should find pulledpork on your link ?

Thank you in advance to answer if I can find pulledpork from your link,

Regards.


Dorian ROSSE.

________________________________
De : Shirkdog <notifications@github.com>
Envoyé : Tuesday, October 16, 2018 10:59:34 PM
À : shirkdog/pulledpork
Cc : Azaretdodo; Author
Objet : Re: [shirkdog/pulledpork] The first adviced command line doesn’t work (#316)


You have several options, but normally you install the necessary perl modules from your OS distribution. The other option is to install them yourself from https://www.cpan.org/

**Comment by Azaretdodo** [comment]
Hello,


Do this perl modules from your link adviced is the need ? :

https://metacpan.org/pod/Net::WebCL

Net::WebCL - LWP::UserAgent base easy web access module.

Thank you in advance to answer if It is the good need,

Regards.


Dorian ROSSE.

________________________________
De : Shirkdog <notifications@github.com>
Envoyé : Tuesday, October 16, 2018 10:59:34 PM
À : shirkdog/pulledpork
Cc : Azaretdodo; Author
Objet : Re: [shirkdog/pulledpork] The first adviced command line doesn’t work (#316)


You have several options, but normally you install the necessary perl modules from your OS distribution. The other option is to install them yourself from https://www.cpan.org/

**Comment by shirkdog** [comment]
What is your UNIX OS?

You need libwww
https://metacpan.org/pod/LWP

On FreeBSD, you would install p5-libwww, so look for these packages on your OS to make it easier.

**Comment by Azaretdodo** [comment]
I will try your advice ;)

Dorian Rosse.

________________________________
De : Shirkdog <notifications@github.com>
Envoyé : mercredi, octobre 17, 2018 14:43
À : shirkdog/pulledpork
Cc : Azaretdodo; Author
Objet : Re: [shirkdog/pulledpork] The first adviced command line doesn’t work (#316)


What is your UNIX OS?

You need libwww
https://metacpan.org/pod/LWP

On FreeBSD, you would install p5-libwww, so look for these packages on your OS to make it easier.

**Comment by Azaretdodo** [comment]
Also I right clic since the blue title for save the link then I do wget « the link » in the pulledpork folder

What should I do next ?

Thank you in advance to follow the problem but now what should I do ?

Regards.


Dorian Rosse.

________________________________
De : Shirkdog <notifications@github.com>
Envoyé : mercredi, octobre 17, 2018 14:43
À : shirkdog/pulledpork
Cc : Azaretdodo; Author
Objet : Re: [shirkdog/pulledpork] The first adviced command line doesn’t work (#316)


What is your UNIX OS?

You need libwww
https://metacpan.org/pod/LWP

On FreeBSD, you would install p5-libwww, so look for these packages on your OS to make it easier.
