### ISSUE TITLE
config file not found

### ISSUE THREAD

**Issue by Azaretdodo** [shirkdog/pulledpork#317]
Hello Dear IT worker,

I copy paste the command line and the finality answer of the command :

**./pulledpork.pl -c pulledpork.conf -i disablesid.conf -T -H
Option H requires an argument

    https://github.com/shirkdog/pulledpork
      _____ ____
     `----,\    )
      `--==\\  /    PulledPork v0.7.4 - Helping you protect your bitcoin wallet!
       `--==\\/
     .-~~~~-.Y|\\_  Copyright (C) 2009-2017 JJ Cummings, Michael Shirk
  @_/        /  66\_  and the PulledPork Team!
    |    \   \   _(")
     \   /-| ||'--'  Rules give me wings!
      \_\  \_\\
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ERROR: Config file not found : pulledpork.conf
 at ./pulledpork.pl line 154.
        main::parse_config_file("pulledpork.conf", HASH(0x5642b9543020)) called at ./pulledpork.pl line 1772**



Thank you in advance to follow the problem,

Regards.


Dorian ROSSE.

**Comment by Azaretdodo** [comment]
OK I found the config file in etc folder I will try the command line from this folder,

Regards.


Dorian ROSSE.

**Comment by Azaretdodo** [comment]
I went to try from etc folder that fail which the missing pulledpork.pl then I try from pulledpork folder which etc in front of the pulledpork.conf which slhash or backslhash but Nothing works :(

anybody has a repair ?

Thank you in advance,

Regards.


Dorian ROSSE.

**Comment by shirkdog** [comment]
The best thing to do is clone this repo, or download the zip into a location so you have all of the necessary files in place.

**Comment by Azaretdodo** [comment]
Yes I am agree I will copy paste the etc folder !

Regards.


Dorian Rosse.
________________________________
