### ISSUE TITLE
Do I need to create a MD5 file where the MD5 hash from my snort version ?

### ISSUE THREAD

**Issue by Azaretdodo** [shirkdog/pulledpork#320]
Hello,

As the title :

_Do I need to create a MD5 file where the MD5 hash from my snort version ?_

Thank you in advance to help follow my ask,

Regards.

Dorian ROSSE.

**Comment by shirkdog** [comment]
You must have a valid version of Snort that is still supported by Cisco/Talos. If you have an out-of-date snort, you may see an HTTP 422 ERROR, which may indicate an out-of-date or EoL version of Snort you are requesting.
