### ISSUE TITLE
rule_url section oinkcode

### ISSUE THREAD

**Issue by Azaretdodo** [shirkdog/pulledpork#324]
hello,

When I launch this command line which a correct oinkcode I have this answer to ask for an oinkcode on line 2101 at rule_url section ::

`./pulledpork.pl -o /usr/local/etc/snort/rules/ -O 'my_oinkcode' -c pulledpork.conf -D ubuntu-18-04 -u https://www.snort.org/rules/snortrules-snapshot-29120.tar.gz -i disablesid.conf -T -H`

> Option H requires an argument
> 
>     https://github.com/shirkdog/pulledpork
>       _____ ____
>      `----,\    )
>       `--==\\  /    PulledPork v0.7.4 - Helping you protect your bitcoin wallet!
>        `--==\\/
>      .-~~~~-.Y|\\_  Copyright (C) 2009-2017 JJ Cummings, Michael Shirk
>   @_/        /  66\_  and the PulledPork Team!
>     |    \   \   _(")
>      \   /-| ||'--'  Rules give me wings!
>       \_\  \_\\
>  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> You need to define an oinkcode, please review the rule_url section of the pulledpork config file!
>  at ./pulledpork.pl line 2101.

Thank you in advance to help me for this problem,

Regards.

Azaretdodo.

**Comment by shirkdog** [comment]
Provide your oinkcode or this stuff does not work.
