### ISSUE TITLE
Create 0.7.4 release

### ISSUE THREAD

**Issue by qha** [shirkdog/pulledpork#333]
0.7.4 is [listed](https://github.com/shirkdog/pulledpork/blob/master/SECURITY.md) as the only supported release but the latest release tagged in git is [0.7.3](https://github.com/shirkdog/pulledpork/releases).

Please create a v0.7.4 tag and push it to Github.

**Comment by shirkdog** [comment]
I am going to need time to get everything into 0.7.4, but I will update the security policy to match the available releases. The issue is everyone should always run master, which will always be the next version of pulledpork. However, for downstream operating systems, it needs to be manageable.

**Comment by qha** [comment]
Looking at this again i realise 0.7.4 isn't ready, sorry i bothered you.
When i created this issue i thought the version in pulledpork.pl meant that release was done and just not tagged for some reason.

**Comment by shirkdog** [comment]
Yes, the version number in pulledpork.pl will always be greater than the available tagged release, mainly because I want to make sure someone is using latest version before they report an issue.
