### ISSUE TITLE
latest perl windows syncing failure

### ISSUE THREAD

**Issue by Azaretdodo** [shirkdog/pulledpork#334]
Hello,

I have It following failure from my printscreen laptop windows (microsoft) 
![pulledpork perl failed](https://user-images.githubusercontent.com/30596513/61958871-7d2b0b80-afc2-11e9-8a5c-51fe4f0a2096.jpg)

Thank you in advance to help me use the latest perl :)

Regards.

azaretdodo.

**Comment by finchy** [comment]
That doesn't appear to be a pulled pork problem.  it looks like your version of perl doesn't match whats in the config file.  Check out the error displayed.

**Comment by Azaretdodo** [comment]
I work on the problem now I fall on It Following errors command line cmd :

'uname' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

ERROR: Temporary file path /tmp/ does not exist.


What I must do now ?

Thank you in advance to bring your help,

Regards.


Dorian ROSSE.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Joel Esler <notifications@github.com>
Envoyé : Friday, July 26, 2019 4:33:36 PM
À : shirkdog/pulledpork <pulledpork@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [shirkdog/pulledpork] latest perl windows syncing failure (#334)


That doesn't appear to be a pulled pork problem. it looks like your version of perl doesn't match whats in the config file. Check out the error displayed.

**Comment by shirkdog** [comment]
You need to set the temp rule path to somewhere that exists on Windows in pulledpork.conf

\# What is our temp path, be sure this path has a bit of space for rule 
\# extraction and manipulation, no trailing slash
temp_path=/tmp

**Comment by Azaretdodo** [comment]
You speak about real directorie your tmp directorie?

Because I don't know how to have an unreal directorie...


Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by Azaretdodo** [comment]
Hello,


I have successfuly set up the tmp file now I have It following error firstly I show the command line :

E:\pulledpork>pulledpork.pl -c pulledpork.conf -l -w -O myoinkcode -o ..\rules\ -s ..\so_rules\ -p ..\Snort\

I have some errors where I know nothing, I have error for snort binarie I have tried ..\Snort\bin then ..\Snort\lib\ then ..\Snort\ then \Snort\ nothing works :(

I have too an error for snort rules tarball in pulledpork conf file gone to line  2120 at pulledpork perl file

![pelledpork conf file](https://user-images.githubusercontent.com/30596513/63338317-daf11000-c342-11e9-8910-c192d092f468.jpg)
![pulledpork perl file](https://user-images.githubusercontent.com/30596513/63338339-e2181e00-c342-11e9-95a5-c7b3131e3698.jpg)

The specified Snort binary does not exist!
Please correct the value or specify the FULL rules tarball name in the pulledpork.conf!
 at E:\pulledpork\pulledpork.pl line 2120.

Thank you in advance to bring your help,

Regards.


Azaretdodo

**Comment by Azaretdodo** [comment]
Well I found the error It was the rules snort tarball :)

Now I have It following errors :

Checking latest MD5 for snortrules-snapshot-29141.tar.gz....
Error downloading https://www.snort.org/rules/snortrules-snapshot-29141.tar.gz.md5?oinkcode=<oinkcode>: 501 Errno architecture (MSWin32-x86-multi-thread-64int-10.0.17763.529) does not match executable architecture (MSWin32-x64-multi-thread-10.0.17134.407) (LWP::Protocol::https not installed) [ 501 ]

What should I do now ?

Thank you in advance to bring your help,

Regards.


Dorian ROSSE.

**Comment by shirkdog** [comment]
Closing this out... the last part of this threat may be OBE due to the latest Snort version being available. Reopen if you are still having issues.
