### ISSUE TITLE
Opensource has been removed

### ISSUE THREAD

**Issue by mesteele101** [shirkdog/pulledpork#345]
It appears SourceFire no longer supports offline event descriptions using the Opensource.gz file :(

Is it possible for all the code related to the Opensource function be removed?

**Comment by shirkdog** [comment]
Yes, it has been removed per Cisco Talos. The goal here is to do a release of 0.7.4 to include this fix as well as others for Snort 3.0 support.

**Comment by shirkdog** [comment]
I just updated pulledpork.pl in the master branch here, there is nothing with opensource.gz mentioned in it. Reopen if you see something.

**Comment by mesteele101** [comment]
Yep, I did see that after I looked :)

There is one section left in the pulledpork.conf mentioning the docs folder

Thanks....
