### ISSUE TITLE
downloading Error

### ISSUE THREAD

**Issue by GooseSteps** [shirkdog/pulledpork#349]
Error downloading https://www.snort.org/rules/snortrules-snapshot-29161.tar.gz.md5?oinkcode=<edit>: 500 Can't connect to www.snort.org:443 (Name or service not known) [ 500 ]

**Comment by finchy** [comment]
Looks like an error in your pulledpork config.

**Comment by GooseSteps** [comment]
the pulledpork.conf based on Snort 2.9.9.x on Ubuntu 14 and 16 file.
the error is 
Checking latest MD5 for snortrules-snapshot-29161.tar.gz....
	No Match
	Done
Rules tarball download of snortrules-snapshot-29161.tar.gz....
	No Match
	Done
Rules tarball download of snortrules-snapshot-29161.tar.gz....
Error downloading https://www.snort.org/rules/snortrules-snapshot-29161.tar.gz?oinkcode=d140fab39cc563e177f0aa4a0becaa3919bf99a1: 500 Can't connect to www.snort.org:443 (Network is unreachable) [ 500 ]

**Comment by GooseSteps** [comment]
PulledPork version is 0.8.0,ubuntu version is 18.04

**Comment by GooseSteps** [comment]
hello，this is my pulledpork.conf
rule_url=https://www.snort.org/reg-rules/|snortrules-snapshot.tar.gz|d8c518576f37e5ed8374e50a7115823d2837767f
rule_url=https://snort.org/downloads/community/|community-rules.tar.gz|Community
rule_url=https://snort.org/downloads/ip-block-list|IPBLOCKLIST|open
ignore=deleted.rules,experimental.rules,local.rules
temp_path=/tmp
rule_path=/etc/snort/rules/snort.rules
local_rules=/etc/snort/rules/local.rules
sid_msg=/etc/snort/sid-msg.map
sid_msg_version=1
sid_changelog=/var/log/sid_changes.log
sorule_path=/usr/local/lib/snort_dynamicrules/
snort_path=/usr/local/bin/snort
config_path=/etc/snort/snort.conf
distro=Ubuntu-18-4
block_list=/etc/snort/rules/iplists/default.blocklist
IPRVersion=/etc/snort/rules/iplists
snort_control=/usr/local/bin/snort_control
version=0.8.1

**Comment by GooseSteps** [comment]
I can find a snortrules-snapshot-29161.tar.gz in /tmp?

**Comment by shirkdog** [comment]
One problem is that version 0.8.1 does not exist, the version in your pulledpork.conf should be set to 0.8.0. After you change that, try this again and see if it is working.

Otherwise you can run pulledpork with "-vvv" for extra verbosity and we can see what is going on. Reopen this issue if it does not work .
