### ISSUE TITLE
Unable to pull down emergingthreatspro rules list

### ISSUE THREAD

**Issue by mandraid** [shirkdog/pulledpork#351]
Error downloading https://rules.emergingthreatspro.com/<my-oinkcode>/snort-3.0.0/etpro.rules.tar.gz.md5: 404 Not Found [ 404 ]
My PulledPork version is v0.8.0.

**Comment by shirkdog** [comment]
Are you trying to use the open source ETPro rules with Snort 3.0? There is a "snort-edge" version that should work if you pass in the "-S" flag with pulledpork, but the rules are the 2.9.x syntax.

**Comment by mandraid** [comment]
Will check it out, thank you!

**Comment by mandraid** [comment]
OK, I am stuck.  Here is what I have: rule_url=https://rules.emergingthreatspro.com/|emerging.rules.tar.gz|snort-edge.  What am I doing wrong? 
This is the response I get: Error downloading https://rules.emergingthreatspro.com/snort-edge/snort-3.0.0/emerging.rules.tar.gz.md5: 404 Not Found [ 404 ]

**Comment by finchy** [comment]
Emerging Threats does not support Snort 3.  That's why this doesn't work.

**Comment by mandraid** [comment]
What is snort edge?

**Comment by finchy** [comment]
The latest version of the Snort ruleset supported I assume.  However, ET does not support the Snort 3 engine.

**Comment by shirkdog** [comment]
The -S option should set the URL in the request, so if you pass -S edge on the CLI it should still download the rules, but like Joel is saying, there is no support for the Snort 3 engine.

**Comment by shirkdog** [comment]
Closing this issue, reopen if it turns out to be an issue with pulledpork
