### ISSUE TITLE
Unable to download Suricata rules

### ISSUE THREAD

**Issue by Calimerorulez** [shirkdog/pulledpork#352]
Hi!

I'm kind of new to Snort/Suricata, but I'm trying to download the Snort rule set for Suricata with pulledpork. I have a paid subscription for the snort rules, so I have an oinkcode.

Trying to download with (I've censored my oinkcode of course):

`./pulledpork.pl -o ./rules/ -O xxxxxxxxxxxxxxxxxxxxxxxxxxxxx -c etc/pulledpork.conf -S suricata-5.0.4`

gives me an error:

```
Checking latest MD5 for snortrules-snapshot-suricata-504.tar.gz....
Error downloading https://www.snort.org/rules/snortrules-snapshot-suricata-504.tar.gz.md5?oinkcode=<oinkcode>: 422 Unprocessable Entity [ 422 ]
```

No matter what version number I try.

Any advise? :)

**Comment by shirkdog** [comment]
There is no suricata ruleset available from snort.org, you will need to use the ET Open or ET PRO URLs and comment out the other "rule_url" settings in your pulledpork.conf

**Comment by Calimerorulez** [comment]
Ok, sorry for my misinterpretation :)
