### ISSUE TITLE
Barnyard2 hangs on the sid file created with pulledpork using: sid_msg_version=2

### ISSUE THREAD

**Issue by mesteele101** [shirkdog/pulledpork#354]
I running, what I think is the latest version of Barnyard 2 from Firnsy's Github site:

```
#define PROGRAM_NAME	"Barnyard"
#define VER_MAJOR	"2"
#define VER_MINOR	"1"
#define VER_REVISION	"14"
#define VER_BUILD	"337"
```
```
# New for by2 and more advanced msg mapping.  Valid options are 1 or 2
# specify version 2 if you are running barnyard2.2+.  Otherwise use 1
sid_msg_version=1
```
Using option '1' allows Barnyard2 to read in the sid file, but using option 2 makes barnyard2 hang up reading in the sid file.

Is there a newer version of Barnyard2 available to use option '2'?

Note: I am compiling Barnyard2 on Windows, that could be the issue?

**Comment by shirkdog** [comment]
There has been less use of Barnyard2, so it may be OBE with other logging mechanisms in use. I have only ever used sid_msg_version=1. I would have to do some testing to see the difference in the files, but would defer to barnyard users.

**Comment by mesteele101** [comment]
There is a huge difference in the files. I wasn’t sure if there was a newer version of Barnyard2 available that I was missing. 

 

Best regards,

Michael...

**Comment by shirkdog** [comment]
I will close this issue for now, but reopen if using sid_msg_version=1 and the most recent barnyard version does not work.
