### ISSUE TITLE
Unknown regexp modifier

### ISSUE THREAD

**Issue by Azaretdodo** [shirkdog/pulledpork#360]
Hello,

I fall on this error when I try to add LWP::UserAgent : 

```
Unknown regexp modifier "/b" at ./pulledpork.pl line 24, at end of line
Unknown regexp modifier "/w" at ./pulledpork.pl line 24, at end of line
Unknown regexp modifier "/w" at ./pulledpork.pl line 24, at end of line
Unknown regexp modifier "/w" at ./pulledpork.pl line 24, at end of line
BEGIN not safe after errors--compilation aborted at ./pulledpork.pl line 24.
```
It is from the libwwwperl github added on /etc/ folder,

in the pulledpork.pl file I have just edited at the line 24 like this :

`use LWP::UserAgent (/lib/libwww-perl);` 

What I should do for go more far ?

Thank you in advance for your help,

Regards.

Azaretdodo.

**Comment by shirkdog** [comment]
You have created a separate Perl issue here. If you are installing a new libwwwperl module, you will want to ensure it gets installed into your Perl installation directories. You can figure out where by running the following:

```perl -e 'print "@INC";'```

You should run ```perl Makefile.PL``` from any modules you download to ensure it gets installed in the proper location. Once you do this, change line 24 back, perl will not interpret the string as a regex and everything should be okay.

**Comment by Azaretdodo** [comment]
Hello,


Two things to do this week-end thanks you for your answer i will install i Hope fully pulledpork if i don't fall on a new error,

I will maybe like use the laster pulledpork ?

This is a bad joke the system is Fedora finaly i miss the BSD file documentation for fully do run snort but i will maybe install again on Ubuntu (and fully !)

Have a nice week from France,

Regards.


Dorian Rosse.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by shirkdog** [comment]
If anything is missing that is BSD related from the official Snort documentation, I will take a look. I will close this issue for now, reopen if you find this does not work.

**Comment by Azaretdodo** [comment]
Hello Michael,


I am in read a Perl 5 book and it is type this command line instead your command line :

[Image]

I am understanding Perl is type perl but should I type the two Slash like it is type ?

Have a Nice evening from France it is sixteen o'clock here,

Regards


Dorian Rosse.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Azaretdodo** [comment]
And does perl use the twice way of quote like python like you do? (" ' " ')

Regards.


Dorian Rosse.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
