### ISSUE TITLE
Snort3 - 422 Unprocessable Entity when trying to download rules 

### ISSUE THREAD

**Issue by ncincotta** [shirkdog/pulledpork#364]
Hello,

Getting the below error when updating Pulled Pork.  Did some searching and tried some things but nothing seems to work around the issue.

**** GET https://www.snort.org/rules/snortrules-snapshot-3170.tar.gz.md5?oinkcode=XXXXX2c4b ==> 422 Unprocessable Entity**

Ubuntu 20.4
Using Pulled Pork V 0.8.0

URL line from Pulled Pork Conf:
rule_url=https://www.snort.org/reg-rules/|snortrules-snapshot.tar.gz|(oinkcode)

Here is my current version of Snort:

   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.1.7.0
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2021 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 3.0.4
           Using LuaJIT version 2.1.0-beta3
           Using OpenSSL 1.1.1j  16 Feb 2021
           Using libpcap version 1.10.0 (with TPACKET_V3)
           Using PCRE version 8.39 2016-06-14
           Using ZLIB version 1.2.11
           Using LZMA version 5.2.5

EDIT:  Is the issue here I'm running 3.1.7.0 but it appears the latest rule is 3150?  I'm not sure if that translates to only 3.1.5.0 meaning a higher version than that has now available rules?

EDIT 2:  Looks like that was it.  I checked other issues and saw you can force a specific version.  I added -S 3.1.50 and works fine!  I was following a guide to install Snort and it pointed me to a resource with 3.1.7.0... although it seems that version isn't even official offered on their website yet.  So a bit strange.

**Comment by finchy** [comment]
If you are using Snort 3, please move to using: https://github.com/shirkdog/pulledpork3

422 means the file does not exist.

**Comment by redbaron4** [comment]
Sourcefire does not release `snortrules-snapshot-xxxx` ruleset for every new version of Snort3. As there is no `snortrules-snapshot-3170.tar.gz` the request returns `422`.

Usually the latest available version (`snortrules-snapshot-3150.tar.gz`) works well with newer releases too so you can use rules for that version. To tell pulledpork to fetch that version add the following to `pulledpork.conf`

```
snort_version=3.1.5.0
```

This disables snort version calculation and fetches rulesets for this version. Same function is available via `-S` command line flag like so: `-S 3.1.5.0`

**Comment by finchy** [comment]
You are correct, however, if you are using Snort 3, you should moved to pulledpork3 as I said above. Pulledpork3 is designed to work with Snort 3.
