### ISSUE TITLE
Feature Request - Teim delay between HUPping processes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shirkdog/pulledpork#89]
```
An option to sleep between HUPping snort/barnyard processes.  I envision 
something like the below in pulledpork.con:

#time to wait between HUPing pids (in seconds)
15


```

Original issue reported on code.google.com by `digital...@gmail.com` on 4 Aug 2011 at 5:24

**Comment by shirkdog** [comment]
Engines have changed over time, will need to evaluate later on for this.

**Comment by shirkdog** [comment]
Closing, HUP code updated and will see if this still is something folks want.
